spring.application.name=inndata020

spring.datasource.url=jdbc:mysql://localhost:3306/inndatadb
spring.datasource.username=root
spring.datasource.password=Nao_DB_650*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACION DE SWAGGER/OPENAPI (Springdoc v2.0.4)
# ==========================================

# Habilitar Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Rutas y configuracion
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Puerto de la aplicacion
server.port=8080
